### ISSUE TITLE
some fdd floppy images are not working

### ISSUE THREAD

**Issue by Tatsuya79** [AZO234/NP2kai#10]
I noticed a couple of games from Mame software list such as dna, amidacho (Amida ChonChon), bbalfin (Battle Block Alfin), inthedun (In the Dungeon) are not working and they are all in fdd format.
But some are working such as atlantia.

Is there something to fix here or are they just bad images?

**Comment by AZO234** [comment]
NP2 can't read .fdd files.  
But it can convert .fdd to raw image(BKDSK, .HD4 file) with VFIC(Virtual Floppy Image Converter).
I can read converted .HD4 files on NP2kai.
To play games, it needs tune some files in .HD4 file.

**Comment by AZO234** [comment]
I added applying to 1.44MB FDD image code.
Please try next buildbot’s output core.

**Comment by Tatsuya79** [comment]
It's working, I can play all 3 fdd games I mentioned before! 👍 
Thank you, closing this now.

Fixed with https://github.com/AZO234/NP2kai/commit/79e8698eb5471a0e99ba5b8abb8eb44eefd0de03
