### ISSUE TITLE
Win98 time is going fast.

### ISSUE THREAD

**Issue by miyamoto999** [AZO234/NP2kai#124]
#123 の動作確認などを行っているときに気がついたのですが、Windows98で時間が高速に進んでいます。

---

I noticed when I was checking #123 operation, etc., that time is moving fast on Windows 98.

**Comment by AZO234** [comment]
以前に、高精度タイマーの実装をNP21/Wの方と行いました。
（Win98インストールが通らなかったため。）
その際に、NP2kaiとNP21/Wの実装に差異があるようになってしまいました。

とりあえず、NP21/Wと同じ実装になるように修正してみます。

**Comment by AZO234** [comment]
I could show Win98's time exceed 4sec per 1min. 😣
I fixed to HRTIMER same NP21/W, but this problem couldn't solve.

**Comment by AZO234** [comment]
お疲れ様です。
Twitterでの動画のご連絡ありがとうございました。

当方で現象が起こせないようで、
ひとまず、HRTIMERの実装をNP21/Wと同じにしました。
何か差異があったかもしれませんので。
ご確認をお願い致します。

I fixed HRTIMER to same as NP21/W.
Could you try that?

**Comment by miyamoto999** [comment]
Twitterで報告したとおり直っているようです。
良かったです。

しかし、
Mac、Windows PC、Linux(VirtualBox、Parallels内)でおこっていたから、
まず、どこでも再現するだろうと思っていたんですけど、
なんで現象が起こらなかったんでしょうね。(うちのPC、何か怪電波の影響でも受けているんだろーか)

まっ、直ったのでよしとしましょう。

お疲れさまでしたー。
