### ISSUE TITLE
[SDL-macOS] Question. Why is mousemng_hidecursor() not called when closing the menu?

### ISSUE THREAD

**Issue by miyamoto999** [AZO234/NP2kai#126]
ちょっと質問です。

sdl/scrnmng.c:443でmacOSの場合、mousemng_hidecursor()を呼ばないようになっているのはなぜ？

mousemng_hidecursor()を呼ぶようにしても問題なさそうなんですが？

---
Question.

Why is mousemng_hidecursor() not called in sdl/scrnmng.c:443 on macOS?

It doesn't seem to be an issue to call mousemng_hidecursor()?

**Comment by AZO234** [comment]
About this feature, I used macOS on VM, I couldn't control mouse.

I checked now, I could use mouse.
I fixed to call mousemng_hidecursor().

Thanks!

**Comment by miyamoto999** [comment]
ありがとうございました。
