### ISSUE TITLE
[Enhancement] speed-up cursor

### ISSUE THREAD

**Issue by cucholix** [AZO234/NP2kai#14]
On consoles the cursor is controlled via d-pad (or analog stick) it's somewhat slow in games that use mouse as input, it would be useful to have a button to speed-up the cursor, for example by holding the "R" button  the cursor goes faster, releasing it goes to normal speed.

Regards

**Comment by AZO234** [comment]
Mouse via D-pad is included with keep D-pad press.
I checked Windows and Linux.
How is it slow?

**Comment by cucholix** [comment]
I can only speak for the Wii U build (my PC can't run RA), so I don't know how the cursor behaive in other platforms. On Wii U it takes 2,29 secs to the cursor go to left end on the screen at the right end.

You are right that it speed-up while keeping d-pad pressed.

**Comment by AZO234** [comment]
I add Joy2Mouse, cursor speed up with during press R1 key.

Regard.

**Comment by cucholix** [comment]
Great, will check it out later, thanks!
