### ISSUE TITLE
Regression in recent core updates (crash to desktop)

### ISSUE THREAD

**Issue by randombyt** [AZO234/NP2kai#142]
After recent updates np2kai core crashes to desktop as soon as it starts. I tested older versions in Retroarch buildbot and last working core version for me is in Retroarch v1.9.11 released on 2021-10-09. np2kai core in Retrparch v1.9.12, v1.9.13 & v1.9.14 all crash on start. 

The errors logged in Retroarch are primarily about failing to write in RA/system/np2kai.

System: Win 8.1 (x64)
Retroarch v1.9.14

**Comment by majintorrinco** [comment]
Having the same problem. Tried with multiple games, including ones that were previously working, always resulting in Retroarch crashing to desktop whil still booting.

I'm attaching the error log if it is of any help. Thanks!

System: Win 10 (x64)
Retroarch v1.10.
[retroarch.log](https://github.com/AZO234/NP2kai/files/7939661/retroarch.log)
0

**Comment by Mah0uPh0x** [comment]
This is also happening to me, with the latest core update and RetroArch nightly (Feb 14). RetroArch crashes with certain games (Touhou 4: Lotus Land Story and Flame Zapper Kotsujin).

System: Windows 11 (x64)
RetroArch 1.10.0 (Feb 14 Nightly)

**Comment by DukeSkinny** [comment]
Here to confirm the issue. All games now crash to desktop during boot.

System: Windows 10 (x64)
RetroArch v1.10.0 (Feb 17 Nightly
[retroarch.log](https://github.com/AZO234/NP2kai/files/8091202/retroarch.log)

**Comment by n1ghttrap** [comment]
Ongoing.  Update?  Possibly related to the PX68K core issues?

**Comment by randombyt** [comment]
Updated the core today and its working properly botting both floppy and hd images. Thanks!

I'll close the issue.
