### ISSUE TITLE
compilation issue (x11 port)

### ISSUE THREAD

**Issue by tokumeiwokiboushimasu** [AZO234/NP2kai#15]
Hi, when compiling X11 port with gcc-7.2.1 on Fedora27, there were the errors bellow.

g++ -DHAVE_CONFIG_H -DSYSRESPATH=\""/usr/local/share/xnp2"\" -I.  -I./.. -I./../
x11 -I./../x11/gtk2 -I./../x11/debug -I./../common -I./../cbus -I./../fdd -I./..
/generic -I./../io -I./../mem -I./../network -I./../sound -I./../sound/fmgen -I.
/../vram -I/usr/include/gtk-2.0 -I/usr/lib64/gtk-2.0/include -I/usr/include/pang
o-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/cairo
 -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr
/include/harfbuzz -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/atk-1.0 -pthread 
 -I/usr/include/SDL2 -D_REENTRANT  -I/usr/include/libusb-1.0    -DSUPPORT_LARGE_
HDD -DSUPPORT_VPCVHD -DSUPPORT_KAI_IMAGES -DHOOK_SYSKEY -DALLOW_MULTIRUN -DSUPPO
RT_NET -DSUPPORT_LGY98 -DUSE_MAME -DSUPPORT_SOUND_SB16    -I./../i286c -DNDEBUG 
-fsigned-char -fno-strict-aliasing -std=c++11 -g -O2 -pthread -c -o ./../x11/ext
/xnp2-opl3.o `test -f './../x11/ext/opl3.cpp' || echo './'`./../x11/ext/opl3.cpp

In file included from /usr/include/c++/7/vector:60:0,
                 from ./../x11/ext/externalchipmanager.h:8,
                 from ./../x11/ext/opl3.cpp:12:
/usr/include/c++/7/bits/stl_algobase.h:243:56: エラー: マクロ "min" に引数が 3 
渡されましたが、2 しか受け取りません
     min(const _Tp& __a, const _Tp& __b, _Compare __comp)
                                                        ^
/usr/include/c++/7/bits/stl_algobase.h:265:56: エラー: マクロ "max" に引数が 3 
渡されましたが、2 しか受け取りません
     max(const _Tp& __a, const _Tp& __b, _Compare __comp)
                                                        ^
In file included from ./../x11/ext/opl3.cpp:6:0:
/usr/include/c++/7/bits/stl_algobase.h:195:5: エラー: expected unqualified-id be
fore ‘const’
     min(const _Tp& __a, const _Tp& __b)
     ^
/usr/include/c++/7/bits/stl_algobase.h:195:5: エラー: expected ‘)’ before ‘co’
/usr/include/c++/7/bits/stl_algobase.h:195:5: エラー: expected ‘)’ before ‘co’
/usr/include/c++/7/bits/stl_algobase.h:195:5: エラー: expected ‘)’ before ‘co’
/usr/include/c++/7/bits/stl_algobase.h:195:5: エラー: expected initializer befor
e ‘const’
/usr/include/c++/7/bits/stl_algobase.h:219:5: エラー: expected unqualified-id be
fore ‘const’
     max(const _Tp& __a, const _Tp& __b)
     ^
/usr/include/c++/7/bits/stl_algobase.h:219:5: エラー: expected ‘)’ before ‘co’
/usr/include/c++/7/bits/stl_algobase.h:219:5: エラー: expected ‘)’ before ‘co’
/usr/include/c++/7/bits/stl_algobase.h:219:5: エラー: expected ‘)’ before ‘co’
/usr/include/c++/7/bits/stl_algobase.h:219:5: エラー: expected initializer befor
e ‘const’
In file included from /usr/include/c++/7/vector:60:0,
                 from ./../x11/ext/externalchipmanager.h:8,
                 from ./../x11/ext/opl3.cpp:12:
/usr/include/c++/7/bits/stl_algobase.h:246:7: エラー: expected primary-expressio
n before ‘if’
       if (__comp(__b, __a))
       ^~
/usr/include/c++/7/bits/stl_algobase.h:246:7: エラー: expected ‘}’ before ‘if’
/usr/include/c++/7/bits/stl_algobase.h:246:7: エラー: expected ‘;’ before ‘if’
/usr/include/c++/7/bits/stl_algobase.h:248:7: エラー: expected unqualified-id be
fore ‘return’
       return __a;
       ^~~~~~
/usr/include/c++/7/bits/stl_algobase.h:268:7: エラー: expected primary-expressio
n before ‘if’
       if (__comp(__a, __b))
       ^~
/usr/include/c++/7/bits/stl_algobase.h:268:7: エラー: expected ‘}’ before ‘if’
/usr/include/c++/7/bits/stl_algobase.h:268:7: エラー: expected ‘;’ before ‘if’
/usr/include/c++/7/bits/stl_algobase.h:270:7: エラー: expected unqualified-id be
fore ‘return’
       return __a;
       ^~~~~~
/usr/include/c++/7/bits/stl_algobase.h:271:5: エラー: expected declaration befor
e ‘}’ token
     }
     ^
make[1]: *** [Makefile:5912: ../x11/ext/xnp2-opl3.o] エラー 1
make[1]: ディレクトリ '/home/hoge/aho/NP2kai/x11' から出ます
make: *** [Makefile:1312: all] エラー 2

**Comment by tokumeiwokiboushimasu** [comment]
We can solve this problem by changing

#ifndef max
#define max(a,b)     (((a) > (b)) ? (a) : (b))
#endif
#ifndef min
#define min(a,b)     (((a) < (b)) ? (a) : (b))
#endif

in x11/compiler.h to

#ifndef np2max
#define np2max(a,b)     (((a) > (b)) ? (a) : (b))
#endif
#ifndef np2min
#define np2min(a,b)     (((a) < (b)) ? (a) : (b))
#endif

, and replace min() -> np2min(), max() -> np2max() in every file that uses these macros.

**Comment by AZO234** [comment]
Thanks your report!

I replaced max()/min() to np2max()/np2min()

Regard.

**Comment by tokumeiwokiboushimasu** [comment]
Thank you for the fix.  But there are some min()'s not fixed in sound/sound.c, sound/cs4231c.c, and a max() in vram/dispsync.c.

**Comment by AZO234** [comment]
Oh, sorry.
I overlooked some files.

I fixed files which you said.

Thanks.

**Comment by tokumeiwokiboushimasu** [comment]
Fixed.  Thanks.
