### ISSUE TITLE
USE_NETWORK=OFF is broken

### ISSUE THREAD

**Issue by jobbautista9** [AZO234/NP2kai#156]
I was trying to build NP2kai in GNU/Hurd, and the latter didn't have the required headers like `tun.h`, so I had to disable network support. It still failed in the end as it was trying to include `x/gtk2/dialog_network.c`, even though I defined `USE_NETWORK` to `OFF`.

**Comment by AZO234** [comment]
I see. That mistake was also made. Sorry.
I'll merge your fix.
Thanks so much.
