### ISSUE TITLE
sudo apt installable version/deb packaging possible?

### ISSUE THREAD

**Issue by MesaBlack** [AZO234/NP2kai#170]
i have a chromebook and the wine i ran on stopped working for some reason.

**Comment by vadosnaprimer** [comment]
We implemented it in out fork BTW (with no changes to the original code):
https://github.com/TASEmulators/NP2kai/tree/tasvideos/debian

**Comment by MesaBlack** [comment]
ah

**Comment by MesaBlack** [comment]
![image](https://github.com/AZO234/NP2kai/assets/132141735/a803218d-e745-42a4-80cd-051735549aa4)
that was amd64. my chromebook runs on intel, probably 64-bit

**Comment by vadosnaprimer** [comment]
amd64 just means 64-bit build, it obviously runs on intel too, but you need a 64-bit OS.

**Comment by MesaBlack** [comment]
oh good. I'm on 64 bit. Why did it fail to retrieve?

**Comment by vadosnaprimer** [comment]
How were you doing it? I install all `deb`s with gdebi.

**Comment by MesaBlack** [comment]
I installed the .deb by itself.

**Comment by MesaBlack** [comment]
and when I click it, it does that

**Comment by MesaBlack** [comment]
> How were you doing it? I install all `deb`s with gdebi.

There's no shortcut icon in Launcher. How do I open it?
