### ISSUE TITLE
[libretro] can't select image file in F12 menu

### ISSUE THREAD

**Issue by Tatsuya79** [AZO234/NP2kai#2]
The path is blank when trying to select a floppy file here on windows 7 x64.
This problem was fixed in the "meow" port at some point.
Perhaps has to do [with this part](https://github.com/libretro/libretro-meowPC98/commit/80975f2349a867be86b6c93c3a661d6b68b24071#diff-e085057b5f77da0dc2653516ea0d6718R189)? (I'm not sure at all)

**Comment by AZO234** [comment]
When I open FDD file selector in F12 menu,
can show files in correct path (System/BIOS folder).
But 'Go to palent folder' button was worse function.

I fixed about Windows path separator in code.
Please try again.

Thanks your kind report.

**Comment by Tatsuya79** [comment]
Thanks I can see the content of the system/np2 folder now and go up twice using the icon.
But I can not go out of Retroarch folder.
It's missing the ".." entry to go up one directory in the file listing.

**Comment by AZO234** [comment]
Sorry my poor fixing.

File selector when over drives root (path is empty),
list drive letters.

About ".." entry is for UNIX like system.
I think unnecessary to Windows.

**Comment by Tatsuya79** [comment]
Thanks that's working great now! 👍 
If empty and you do "up directory", it goes from np2 to system to "Drive letters".
That works fine.
Great work.
