### ISSUE TITLE
No longer compiles on Windows

### ISSUE THREAD

**Issue by Tatsuya79** [AZO234/NP2kai#23]
Hi, it's failing here with Msys2 for windows x64:
https://pastebin.com/cN6bV3bA

**Comment by AZO234** [comment]
I fixed dosio.c.

By the way, How can I look buildlog of buildbot?

**Comment by Tatsuya79** [comment]
Thanks, I could compile it fine now, closing this.
[I've done the system dir name change to the core info too.](https://github.com/libretro/libretro-super/pull/731)
