### ISSUE TITLE
Steam Hearts hd image doesn't boot

### ISSUE THREAD

**Issue by i30817** [AZO234/NP2kai#28]
The hd image from the pc98 internet archive collection. I dunno if it's made badly or not but it boots in Anex86, so something seems fishy. Different default settings maybe?

**Comment by AZO234** [comment]
I don't know that image file.
Can you tell me HD image file's hash?

**Comment by i30817** [comment]
md5: 52ffbcde843085a4a2b5cc285ce10e84
sha256: d71221b8a6c276530e655d047b53d80fe993aef75c15c880ecfc25b78a8ccf14
crc32: 5538e913

I forgot to tell it was part of the Neko Kobe collection...
https://archive.org/download/NeoKobe-NecPc-98012017-11-17

It's inside 'Giga.zip' here, ask me, or delete the post yourself to remove link if you'd prefer not to have it on the repository bug reports.

**Comment by i30817** [comment]
[You can still download it with a direct link](https://archive.org/download/NeoKobe-NecPc-98012017-11-17/Giga.zip)

Remove the link after checking the error I guess

**Comment by AZO234** [comment]
I tried that hdi file. I didn't see nothing to problem.

On PC-98, if a floppy is not inserted(boot from HD), HD is assigned to 'A:'.

**Comment by i30817** [comment]
Did it start the game for you? I'm using the retroarch core version if i didn't mention it yet ( should be no problem because they just shallow clone right?)

**Comment by AZO234** [comment]
I start from XMB menu.

**Comment by i30817** [comment]
No difference.

**Comment by i30817** [comment]
It was the cfg file. I must have changed the DIP switch for another game and forgot all about it.

Man do these games need a config database...
