### ISSUE TITLE
font

### ISSUE THREAD

**Issue by tokumeiwokiboushimasu** [AZO234/NP2kai#29]
Hi, in the web page and README.md, there's no description about FONT.BMP (not FONT.ROM).
But, without FONT.BMP, np2kai displays very ugly characters. 
We can use either font.bmp or FONT.BMP with xnp2kai.

**Comment by AZO234** [comment]
I wrote about FONT.BMP to README.md and my site.  
I recommend FONT.BMP's file name is BIG LETTER for UNIX (for SDL2 not xnp2kai).

**Comment by tokumeiwokiboushimasu** [comment]
Thank you.
