### ISSUE TITLE
build issue (x11 version)

### ISSUE THREAD

**Issue by tokumeiwokiboushimasu** [AZO234/NP2kai#33]
Hi, I'm using gcc-7.3.1 on Fedora27.  The build fails with the errors bellow.

./../x11/gtk2/dialog_ide.c: 関数 ‘ok_button_clicked’ 内:
./../x11/gtk2/dialog_ide.c:45:14: エラー: ‘NP2CFG {aka struct tagNP2Config}’ ‘idetype’ という名前のメンバを持っていません
    if (np2cfg.idetype[0] != i) {
              ^
./../x11/gtk2/dialog_ide.c:46:11: エラー: ‘NP2CFG {aka struct tagNP2Config}’ ‘idetype’ という名前のメンバを持っていません
     np2cfg.idetype[0] = i;
           ^
./../x11/gtk2/dialog_ide.c:54:14: エラー: ‘NP2CFG {aka struct tagNP2Config}’ ‘idetype’ という名前のメンバを持っていません
    if (np2cfg.idetype[1] != i) {
              ^
./../x11/gtk2/dialog_ide.c:55:11: エラー: ‘NP2CFG {aka struct tagNP2Config}’ ‘idetype’ という名前のメンバを持っていません
     np2cfg.idetype[1] = i;
           ^
./../x11/gtk2/dialog_ide.c:63:14: エラー: ‘NP2CFG {aka struct tagNP2Config}’ ‘idetype’ という名前のメンバを持っていません
    if (np2cfg.idetype[2] != i) {
              ^
./../x11/gtk2/dialog_ide.c:64:11: エラー: ‘NP2CFG {aka struct tagNP2Config}’ ‘idetype’ という名前のメンバを持っていません
     np2cfg.idetype[2] = i;
           ^
./../x11/gtk2/dialog_ide.c:72:14: エラー: ‘NP2CFG {aka struct tagNP2Config}’ ‘idetype’ という名前のメンバを持っていません
    if (np2cfg.idetype[3] != i) {
              ^
./../x11/gtk2/dialog_ide.c:73:11: エラー: ‘NP2CFG {aka struct tagNP2Config}’ ‘idetype’ という名前のメンバを持っていません
     np2cfg.idetype[3] = i;
           ^
./../x11/gtk2/dialog_ide.c:83:12: エラー: ‘NP2CFG {aka struct tagNP2Config}’ h no member named ‘iderwait’; did you mean ‘wait’?
  if(np2cfg.iderwait != temp) {
            ^~~~~~~~
            wait
./../x11/gtk2/dialog_ide.c:84:10: エラー: ‘NP2CFG {aka struct tagNP2Config}’ h no member named ‘iderwait’; did you mean ‘wait’?
   np2cfg.iderwait = temp;
          ^~~~~~~~
          wait
./../x11/gtk2/dialog_ide.c:90:12: エラー: ‘NP2CFG {aka struct tagNP2Config}’ h no member named ‘idewwait’; did you mean ‘wait’?
  if(np2cfg.idewwait != temp) {
            ^~~~~~~~
            wait
./../x11/gtk2/dialog_ide.c:91:10: エラー: ‘NP2CFG {aka struct tagNP2Config}’ h no member named ‘idewwait’; did you mean ‘wait’?
   np2cfg.idewwait = temp;
          ^~~~~~~~
          wait
./../x11/gtk2/dialog_ide.c:95:13: エラー: ‘NP2CFG {aka struct tagNP2Config}’ h no member named ‘idebios’; did you mean ‘usebios’?
  if (np2cfg.idebios != useidebios) {
             ^~~~~~~
             usebios
./../x11/gtk2/dialog_ide.c:96:10: エラー: ‘NP2CFG {aka struct tagNP2Config}’ h no member named ‘idebios’; did you mean ‘usebios’?
   np2cfg.idebios = useidebios;
          ^~~~~~~
          usebios
./../x11/gtk2/dialog_ide.c:99:13: エラー: ‘NP2CFG {aka struct tagNP2Config}’ h no member named ‘autoidebios’; did you mean ‘usebios’?
  if (np2cfg.autoidebios != autoidebios) {
             ^~~~~~~~~~~
             usebios
./../x11/gtk2/dialog_ide.c:100:10: エラー: ‘NP2CFG {aka struct tagNP2Config}’ s no member named ‘autoidebios’; did you mean ‘usebios’?
   np2cfg.autoidebios = autoidebios;
          ^~~~~~~~~~~
          usebios
./../x11/gtk2/dialog_ide.c: 関数 ‘create_ide_dialog’ 内:
./../x11/gtk2/dialog_ide.c:195:71: エラー: ‘NP2CFG {aka struct tagNP2Config}’  ‘idetype’ という名前のメンバを持っていません
  gtk_entry_set_text(GTK_ENTRY(drivetype_pm_entry),drivetype_str[np2cfg.idetype[
0]]);
                                                                       ^
./../x11/gtk2/dialog_ide.c:207:71: エラー: ‘NP2CFG {aka struct tagNP2Config}’  ‘idetype’ という名前のメンバを持っていません
  gtk_entry_set_text(GTK_ENTRY(drivetype_sm_entry),drivetype_str[np2cfg.idetype[
2]]);
                                                                       ^
./../x11/gtk2/dialog_ide.c:225:71: エラー: ‘NP2CFG {aka struct tagNP2Config}’  ‘idetype’ という名前のメンバを持っていません
  gtk_entry_set_text(GTK_ENTRY(drivetype_ps_entry),drivetype_str[np2cfg.idetype[
1]]);
                                                                       ^
./../x11/gtk2/dialog_ide.c:237:71: エラー: ‘NP2CFG {aka struct tagNP2Config}’  ‘idetype’ という名前のメンバを持っていません
  gtk_entry_set_text(GTK_ENTRY(drivetype_ss_entry),drivetype_str[np2cfg.idetype[
3]]);
                                                                       ^
./../x11/gtk2/dialog_ide.c:254:13: エラー: ‘NP2CFG {aka struct tagNP2Config}’ s no member named ‘iderwait’; did you mean ‘wait’?
  if (np2cfg.iderwait >= 0 && np2cfg.iderwait <= 100000000) {
             ^~~~~~~~
             wait
./../x11/gtk2/dialog_ide.c:254:37: エラー: ‘NP2CFG {aka struct tagNP2Config}’ s no member named ‘iderwait’; did you mean ‘wait’?
  if (np2cfg.iderwait >= 0 && np2cfg.iderwait <= 100000000) {
                                     ^~~~~~~~
                                     wait
./../x11/gtk2/dialog_ide.c:255:30: エラー: ‘NP2CFG {aka struct tagNP2Config}’ s no member named ‘iderwait’; did you mean ‘wait’?
   sprintf(temp, "%d", np2cfg.iderwait);
                              ^~~~~~~~
                              wait
./../x11/gtk2/dialog_ide.c:259:10: エラー: ‘NP2CFG {aka struct tagNP2Config}’ s no member named ‘iderwait’; did you mean ‘wait’?
   np2cfg.iderwait = 100000000;
          ^~~~~~~~
          wait
./../x11/gtk2/dialog_ide.c:283:13: エラー: ‘NP2CFG {aka struct tagNP2Config}’ s no member named ‘idewwait’; did you mean ‘wait’?
  if (np2cfg.idewwait >= 0 && np2cfg.idewwait <= 100000000) {
             ^~~~~~~~
             wait
./../x11/gtk2/dialog_ide.c:283:37: エラー: ‘NP2CFG {aka struct tagNP2Config}’ s no member named ‘idewwait’; did you mean ‘wait’?
  if (np2cfg.idewwait >= 0 && np2cfg.idewwait <= 100000000) {
                                     ^~~~~~~~
                                     wait
./../x11/gtk2/dialog_ide.c:284:30: エラー: ‘NP2CFG {aka struct tagNP2Config}’ s no member named ‘idewwait’; did you mean ‘wait’?
   sprintf(temp, "%d", np2cfg.idewwait);
                              ^~~~~~~~
                              wait
./../x11/gtk2/dialog_ide.c:288:10: エラー: ‘NP2CFG {aka struct tagNP2Config}’ s no member named ‘idewwait’; did you mean ‘wait’?
   np2cfg.idewwait = 100000000;
          ^~~~~~~~
          wait
./../x11/gtk2/dialog_ide.c:309:13: エラー: ‘NP2CFG {aka struct tagNP2Config}’ s no member named ‘idebios’; did you mean ‘usebios’?
  if (np2cfg.idebios) {
             ^~~~~~~
             usebios
./../x11/gtk2/dialog_ide.c:316:13: エラー: ‘NP2CFG {aka struct tagNP2Config}’ s no member named ‘autoidebios’; did you mean ‘usebios’?
  if (np2cfg.autoidebios) {
             ^~~~~~~~~~~
             usebios
make[1]: *** [Makefile:4445: ../x11/gtk2/xnp2kai-dialog_ide.o] エラー 1
make: *** [Makefile:1321: all] エラー 2

**Comment by AZO234** [comment]
Sorry for my mistake.
I fixed compile.h.

Please try again.

**Comment by tokumeiwokiboushimasu** [comment]
Fixed.  Thanks.
