### ISSUE TITLE
[X11] No beep sound with INT 1CH AH=06H

### ISSUE THREAD

**Issue by frank-deng** [AZO234/NP2kai#37]
I tried to use the BIOS's beep function with the following code, but failed to produce any sound.
```
#include <stdio.h>
#include <dos.h>

union REGS inregs, outregs;

void main(){
	inregs.h.ah = 0x06;
	inregs.x.cx = 1;
	inregs.x.dx = 1000;
	int86y(0x1C, &inregs, &outregs);
}
```
[LSI C-86 Ver. 3.30c試食版](https://www.lsi-j.co.jp/freesoft/index.html) is used for compiling the code above inside the PC98 emulator.

**Comment by AZO234** [comment]
To sound beep, we must write value to timer with address, without interrupt.
(PC-98 is not AT machine.)
