### ISSUE TITLE
Is it possible to reduce the CPU load when system is idle?

### ISSUE THREAD

**Issue by frank-deng** [AZO234/NP2kai#38]
For example: Use `dosidle.exe` which makes use of CPU's HLT instruction.

**Comment by AZO234** [comment]
In follow link, "IDLE.COM and WQGHLT.386 is work on NP21."
http://anago.5ch.net/test/read.cgi/software/1405645007/375

I didn't try this.

**Comment by frank-deng** [comment]
When running `IDLE.COM` under NP2, the CPU usage was reduced to under 10% when idle, and my laptop no longer gets too hot when running NP2.
Thanks!
