### ISSUE TITLE
[libretro] crash on start win x64

### ISSUE THREAD

**Issue by Tatsuya79** [AZO234/NP2kai#51]
NP2Kai libretro crashes on start on windows 7 x64.
Last good build was e07bf317d5cec80335a6abcb468b639fc78ab373.

Sorry I can't find anything helpful in the log and can not compile it with DEBUG (it's failing here with MSYS2 gcc 7.3).

**Comment by AZO234** [comment]
I fixed rev.17 Windows port.
Disable of the function was not enough.

Regard.

**Comment by Tatsuya79** [comment]
Thank you it works fine now!

We forked your repository to the libretro organization and are building from it to maintain it as we told you.
We were on a previous working commit but we'll update the changes now.

So don't be surprised if you make change and the builbot logs on discord is not showing anything for this repository now.

Take care.
