### ISSUE TITLE
SDL2 compilation in macOS fails with a single error.

### ISSUE THREAD

**Issue by Art10001** [AZO234/NP2kai#54]
../network/net.c:68:10: fatal error: 'linux/if.h' file not found

In the network directory, there are the following files: `lgy98.c    lgy98.h    lgy98.o    lgy98dev.h net.c      net.h      readme.txt` but no if.h.

EDIT: if.h exists under <net/if.h>, if_ether.h under <netinet/if_ether.h> but if_tun.h does not seemingly exist.

EDIT2: added where if_ether.h is located at and a clarification.

**Comment by AZO234** [comment]
NP2kai does not support SDL2 build on Mac.
I do not know how to build and necessary libraries.

According to your report, dependency of header file seems to be complicated.
I am sorry, but I will not correspond.

Thanks.

**Comment by AZO234** [comment]
I added Makefile.mac.

$ make -f Makefile.mac
then maked np2kai executable file.
(You can use Makefile21.mac too.)

Please try it.

**Comment by Art10001** [comment]
Thank you! :D

2018-07-07 2:38 GMT-04:00 AZO <notifications@github.com>:

**Comment by Art10001** [comment]
@AZO234 , the compilation works, the executable runs, but the button to show GUI is used by the "Show Desktop" function of Mission Control (an hotkey that shows the desktop quickly).

I changed the binding, and the GUI works, but the mouse can barely move, as the instant it moves it is locked back to the center of the window.

**Comment by AZO234** [comment]
There was a report on RetroArch of Mac that mouse operation is not good.
Is it a problem with SDL?

About the header file of the network, it seems that it is not just the difference of the directory.
Another implementation is required.

I was informing RA developers,  
I currently refraining from developing NP2kai for health reasons.  
I'm sorry, I don't have the power to solve problems now.

Regard.

**Comment by bmosley** [comment]
> I changed the binding, and the GUI works, but the mouse can barely move, as the instant it moves it is locked back to the center of the window.

I'm experiencing the same issue. building from source (no x11) The mouse resets back to center when attempting to select GUI menu. Unable to use

**Comment by AZO234** [comment]
Since I do not own a Mac,
I operated macOS with a simulator and confirmed the build of NP2kai.
However, it has not been sufficiently inspected until operation.

The mouse cursor is not fixed in the center.
But there seems to be a problem with GUI operation as well.
It will take time to fix it.

**Comment by bmosley** [comment]
Are there hotkeys or keyboard shortcuts to use as workaround?

**Comment by AZO234** [comment]
The GUI key of NP2 is currently assigned to F12 key.
When using on a Mac, which key should I assign?

**Comment by bmosley** [comment]
i think F12 is fine for GUI. Is there a modifier key to select one of the gui menu items without using mouse? like ALT or so?

**Comment by AZO234** [comment]
I examined it in detail.
When clicking the mouse, the coordinates pointed to the center of the screen.
I finally understood the phenomenon.
We changed the coordinates when moving the mouse and use that coordinates when clicking.
I loaded FD and HDD and confirmed that the game can operate.

**Comment by bmosley** [comment]
Excellent AZO! Have you commit the change?

**Comment by Art10001** [comment]
Since this seems to be solved... I close it. Thank you for your help.
