### ISSUE TITLE
X11 compilation in Debian 9 Stable ("Stretch") fails

### ISSUE THREAD

**Issue by Art10001** [AZO234/NP2kai#55]
undefined reference
     to symbol 'pthread_create@@GLIBC_2.1'

And there's also something missing with a command called ACX or something like that (I had to shut down the PC: will update with more logs soon)

I installed more or less 5 libraries that menction pthread, including libevent and dev libs. I saw that there were debugging symbols that could help, but they are in Buster (current Debian Testing) and in Sid (Debian Unstable).

SDL2 compilation does work, but the twitchiness of clicking in menus (you go to the menu and the button flashes a ton of times, like if it was selected and then released constantly, two or three times per second? also happens with mac) is a bit unwieldy.

You are free to not provide support for this particular failure in compilation, as Debian Stable is known for shipping with very old software that is barely updated (if at all, except for security fixes) until the next release, which happens in 3 year periods (approximately). For work reasons, I am unable to change the PC's repositories to Debian Testing.

**Comment by AZO234** [comment]
Thanks to your report!

I confirmed the problem with Raspbian.
I think that the macro of autoconf is insufficient.

Please try installing 'autoconf-archive'.
$ sudo apt install autoconf-archive

**Comment by Art10001** [comment]
Indeed, the installation of autoconf-archive has fixed the X11 compilation errors. Thank you.
