### ISSUE TITLE
Libretro core fails to compile (win)

### ISSUE THREAD

**Issue by Tatsuya79** [AZO234/NP2kai#61]
Hi, I can not compile the libretro core using MSYS2 Mingw64 gcc 7.3.
[This is the log I get.](https://pastebin.com/JZ1BuEhQ)

Thank you.

**Comment by AZO234** [comment]
Sorry, I forgot adding source directory to Makefile.
I fixed.

Thanks!

**Comment by Tatsuya79** [comment]
Thanks it compiled fine now! :+1:
