### ISSUE TITLE
Compilation under Windows 7 MinGW64/32 fails.

### ISSUE THREAD

**Issue by Art10001** [AZO234/NP2kai#62]
After a lot of tries, I finally got NP2Kai to almost compile. First, it complained that -lmingw32 was not found. I realized that the resulting executable would be 32 bits, so I installed the 32 bits toolchain version that you specify on the README.

However, I get the following issue:

"../sdl2/win32/main.o: file not recognized: File format not recognized
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile21.win:67: np21kai] Error 1"

This is the text of sdl2/win32/main.c:

"/**
 * @file	main.c
 * @brief	C
 */

#include "compiler.h"
#include "np2.h"
#include "..\fontmng.h"

#pragma comment(lib, "SDL2.lib")
#pragma comment(lib, "SDL2main.lib")
#pragma comment(lib, "zlib.lib")

#if !defined(RESOURCE_US)
#pragma comment(lib, "SDL2_ttf.lib")
#endif

/**
 * C
 * @param[in] argc ø
 * @param[in] argv ø
 * @return Ug R[h
 */
int main(int argc, char *argv[])
{
	UINT nLength;
	TCHAR szFont[MAX_PATH];

	nLength = GetWindowsDirectory(szFont, SDL_arraysize(szFont));
	lstrcpy(szFont + nLength, TEXT("\\Fonts\\msgothic.ttc"));
	fontmng_setdeffontname(szFont);

	return np2_main(argc, argv);
}"

What could be the issue?

Also, it's worth menctioning that during compilation, an error was obtained: in the sdl2/dosio.c file, in the 193th line, there's a bug, as mkdir() only accepts one instruction. You can fix this by transforming it into _mkdir.

Thank you for your help!

**Comment by AZO234** [comment]
I tuned SDL2 build on Windows(MSYS2 64bit's 32bit console).

It needs installing 'mingw-w64-i686-SDL2' etc and 'mingw-w64-i686-gcc' packages.
I fixed README.

Sorry to your inconvenience.

**Comment by Art10001** [comment]
After many months, I realized that I had forgotten to comment here.

Well, I had compiled NP2Kai, and it worked, but I dislike the SDL2 GUI and find it lacking in features the X11 port has.

Sorry for leaving this issue open for so long!
