### ISSUE TITLE
The icon of the program in the X11 port is colour inverted.

### ISSUE THREAD

**Issue by Art10001** [AZO234/NP2kai#68]
In other words, both the icon that's shown at the upper left corner of NP2Kai and the taskbar icon are black with a white background, instead of white with an invisible background, as can be seen here:

![example](https://user-images.githubusercontent.com/18252185/55036444-6dda8800-4ff9-11e9-8259-bc0fca3db6a1.jpg)

Please fix it, and thank you! :D

**Comment by AZO234** [comment]
Oh, thank you.
Icon picture is XBM monoclome type,  
It may be inverted depending on the settings of the distribution and X server.
Is this your X is XFCE?

**Comment by AZO234** [comment]
Yeah, fixed!
but, black Neko is cute too...

**Comment by Art10001** [comment]
Yes, the DE I was using was XFCE.
Thank you! :D
