### ISSUE TITLE
 BIOS files ?

### ISSUE THREAD

**Issue by 3r1kd0f** [AZO234/NP2kai#88]
Thank you for developing this emulator - this is super cool to have something running on Linux.

Sorry if my question is stupid...but where can I find BIOS files ?

From what I have found on internet some specific files are needed but it is not clear how to generate or where to find those.

np2kai/font.bmp
np2kai/FONT.ROM
np2kai/bios.rom
np2kai/itf.rom
np2kai/sound.rom
np2kai/2608_bd.wav
np2kai/2608_sd.wav
np2kai/2608_top.wav
np2kai/2608_hh.wav
np2kai/2608_tom.wav
np2kai/2608_rim.wav

Thanks in advance !

**Comment by AZO234** [comment]
Create the BIOS files from your PC-98 and use them only by yourself.

Start MS-DOS on the actual PC-98  
and execute the GETBIOS command (included in the np2tool/np2tool.zip floppy image)  
to create the BIOS file.

**Comment by 3r1kd0f** [comment]
Thanks for the answer !
