### ISSUE TITLE
Black screen when loading d88 disk

### ISSUE THREAD

**Issue by 3r1kd0f** [AZO234/NP2kai#89]
When I try to run games in d88 format with `xnp21kai`, I get a black screen (after RAM check). 
Running games in hdi files goes without any issue.

Note that running the same d88 game with m88 emulator works without issue.

Are there steps to follow to debug ?

I have build NP2kai on Manjaro based on code with commit `82a79e077568bf9deff37e49dac48596cb1163e3`

Many thanks

**Comment by AZO234** [comment]
NP2kai is PC98 emulator.
M88 emulator? It's PC88 emulator, different architecture.
How about other PC88 emu, for example quasi88.

Regard.

**Comment by 3r1kd0f** [comment]
Thanks for the clarification.
I got confused because I saw that d88 and d98 files are supported.
