### ISSUE TITLE
static assertion failed

### ISSUE THREAD

**Issue by mrennekamp** [AZO234/NP2kai#91]
In file included from /usr/include/c++/10/bits/move.h:57,
                 from /usr/include/c++/10/bits/stl_pair.h:59,
                 from /usr/include/c++/10/bits/stl_algobase.h:64,
                 from /usr/include/c++/10/vector:60,
                 from ./../x11/ext/externalchipmanager.h:8,
                 from ./../x11/ext/opl3.cpp:12:
/usr/include/c++/10/type_traits:200:44: error: expected primary-expression before ‘)’ token
  200 |   template <typename _T, size_t = sizeof(_T)>
      |                                            ^
/usr/include/c++/10/type_traits:201:70: error: wrong number of template arguments (0, should be 1)
  201 |     constexpr true_type __is_complete_or_unbounded(__type_identity<_T>)
      |                                                                      ^
/usr/include/c++/10/type_traits:95:12: note: provided for ‘template<class _Type> struct std::__type_identity’
   95 |     struct __type_identity
      |            ^~~~~~~~~~~~~~~
/usr/include/c++/10/type_traits: In instantiation of ‘struct std::is_copy_assignable<std::_Rb_tree_node_base*>’:
/usr/include/c++/10/type_traits:138:12:   required from ‘struct std::__and_<std::is_copy_assignable<std::_Rb_tree_node_base*>, std::is_copy_assignable<std::_Rb_tree_node_base*> >’
/usr/include/c++/10/bits/stl_pair.h:389:7:   required from ‘struct std::pair<std::_Rb_tree_node_base*, std::_Rb_tree_node_base*>’
/usr/include/c++/10/bits/stl_tree.h:2077:49:   required from here
/usr/include/c++/10/type_traits:1097:52: error: static assertion failed: template argument must be a complete class or an unbounded array
 1097 |       static_assert(std::__is_complete_or_unbounded(__type_identity<_Tp>{}),
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/10/type_traits: In instantiation of ‘struct std::is_move_assignable<std::_Rb_tree_node_base*>’:
/usr/include/c++/10/type_traits:138:12:   required from ‘struct std::__and_<std::is_move_assignable<std::_Rb_tree_node_base*>, std::is_move_assignable<std::_Rb_tree_node_base*> >’
/usr/include/c++/10/bits/stl_pair.h:400:7:   required from ‘struct std::pair<std::_Rb_tree_node_base*, std::_Rb_tree_node_base*>’
/usr/include/c++/10/bits/stl_tree.h:2077:49:   required from here
/usr/include/c++/10/type_traits:1118:52: error: static assertion failed: template argument must be a complete class or an unbounded array
 1118 |       static_assert(std::__is_complete_or_unbounded(__type_identity<_Tp>{}),
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
make[1]: *** [Makefile:14158: ../x11/ext/xnp2kai-opl3.o] Error 1

**Comment by mrennekamp** [comment]
wait, I saw it was related to 4 issues, let me see how to reverse it or merge into another

**Comment by AZO234** [comment]
Thanks interesting report.  
I'm just trying 'character' issue.  
It is affect something, maybe Windows's _T macro.
I'll take care.
