### ISSUE TITLE
(Retroarch) Games not loading correctly.

### ISSUE THREAD

**Issue by demodanza** [AZO234/NP2kai#93]
I have made no changes to my setup, but for some reason PC-98 games no longer load, they just display the "How many files(0-15)?" text, when before they loaded directly into the game.

Tested it with hdi, fdi and d88 formats on a Windows 10 and a Windows 7 x64 machine. Bios on core information seems to be ok, all optional files included.

EDIT: Seems that games with no spaces in their filenames load fine. Is this intended behavior?

Also, the core does not detect m3u files.

**Comment by AZO234** [comment]
Thanks! I just fixed yesterday.
See https://github.com/AZO234/NP2kai/issues/90 .

**Comment by demodanza** [comment]
It was fixed, thanks! However, now hdi files don't load, just tested on Android.

**Comment by AZO234** [comment]
I got it. I check.
Thanks.

**Comment by AZO234** [comment]
Did you use out of '/storage/emulated/0' files?
