### ISSUE TITLE
Libretro - PSP build failure

### ISSUE THREAD

**Issue by twinaphex** [AZO234/NP2kai#94]
Hi there,

can you fix NP2Kai for RetroArch PSP? Right now the PSP build fails to compile because of NP2Kai.

See the error log here -

http://paste.libretro.com/201840

In specific -

-- Building core: np2kai --
NAME: np2kai
ASYNC: 0
LTO: 0
make: Entering directory '/home/buildbot/buildbot/psp/retroarch'
psp-gcc -Ideps -Ideps/stb -Ideps/7zip -Ideps/pthreads -Ideps/pthreads/platform/psp -Ideps/pthreads/platform/helper -Ilibretro-common/include -Ilibretro-common/include/compat/zlib -I. -I/home/buildbot/tools/devkitpro/devkitPSP/psp/sdk/include -O3 -G0 -std=gnu99 -ffast-math -fsingle-precision-constant -DHAVE_KERNEL_PRX -DPSP -D_MIPS_ARCH_ALLEGREX -DHAVE_LANGEXTRA -DHAVE_ZLIB -DHAVE_AUDIOMIXER -DHAVE_RPNG -DHAVE_RJPEG -DHAVE_GRIFFIN=1 -DRARCH_INTERNAL -DRARCH_CONSOLE -DHAVE_MENU -DHAVE_CONFIGFILE -DHAVE_RGUI -DHAVE_FILTERS_BUILTIN -DHAVE_7ZIP -DHAVE_CC_RESAMPLER -DHAVE_THREADS -D_PSP_FW_VERSION=150  -L. -L/home/buildbot/tools/devkitpro/devkitPSP/psp/sdk/lib   griffin/griffin.o bootstrap/psp1/kernel_functions.o  -lretro_psp1  -lstdc++ -lpspgu -lpspgum -lm -lpspaudio -lpspfpu -lpsppower -lpsprtc -lpspdebug -lpspdisplay -lpspge -lpspctrl -lpspsdk -lc -lpspnet -lpspnet_inet -lpspnet_apctl -lpspnet_resolver -lpsputility -lpspuser -lpspkernel -o retroarchpsp.elf
./libretro_psp1.a(pccore.o): In function `QueryPerformanceCounter':
(.text+0x2ee8): undefined reference to `NP2_TickCount_GetCount'
./libretro_psp1.a(pccore.o): In function `QueryPerformanceFrequency':
(.text+0x2f28): undefined reference to `NP2_TickCount_GetFrequency'
collect2: ld returned 1 exit status
/home/buildbot/tools/devkitpro/devkitPSP/psp/sdk/lib/build.mak:176: recipe for target 'retroarchpsp.elf' failed
make: *** [retroarchpsp.elf] Error 1

**Comment by AZO234** [comment]
I saw it, and I checked 7197410 fixed to suppress those symbols when PSP.
(old library linked?)
Please can you retry build?

**Comment by AZO234** [comment]
Prease NP2kai build again, then link to RetroArch.

**Comment by AZO234** [comment]
Anyway, I found bug, send request you!

**Comment by AZO234** [comment]
I saw RetroArch's link error on PSP.
I'm sorry.
I fixed more to symbol.
