### ISSUE TITLE
Save state greyed out

### ISSUE THREAD

**Issue by arBalasquide** [AZO234/NP2kai#97]
I'm new to PC-98 emulation and I'm trying to play a .HDI game. However, I want to save the state of the game but the "Stat" option only shows "Empty". What do I need to do to enable it?

Running latest master branch i386 version on Linux 5.6.10. 

日本語の説明もおＫです。

**Comment by AZO234** [comment]
NP2's state save function is hidden.
(Because it is modified often, and not be implemented enough yet.
When it is modified, older state files can't use.)

If You teｓｔ it, write "STATSAVE = true" to .config/xnp2kai/xnp2kairc.

See too.
https://www.nonakap.org/np2/html/help/ja/othercfg.html

**Comment by arBalasquide** [comment]
Ah, that was stupid of me not to figure out. Thank you for the help and the extra information :)!
