### ISSUE TITLE
Libretro - Vita build failure

### ISSUE THREAD

**Issue by twinaphex** [AZO234/NP2kai#98]
Hi there, the Vita build currently fails -

http://paste.libretro.com/209339

I'll have to disable the port for now for Vita so that our nightly builds still work, but I'd appreciate it if you could look into this and fix it so it can be re-enabled soon.

**Comment by twinaphex** [comment]
Wait, never mind, this is another core - 

https://github.com/libretro/libretro-meowPC98

Disregard, I will close the issue. There is no issue here.

BTW, is meowPC98 an outdated version of NP2Kai?

**Comment by AZO234** [comment]
Hi.

I don't (almost) relate meowPC98.
Then I don't know who and how maintenance it.

But I hear users say 'Not work on NP2kai, work on meowPC98' rarely.
When that is, I fix NP2kai code, not reference to meowPC98.

Regard.


2020年5月30日(土) 9:09 Autechre <notifications@github.com>:
